# Generated by Django 3.0.7 on 2020-07-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_cap', models.CharField(max_length=100)),
                ('brand_desc', models.TextField(null='fd')),
                ('dealership_loc', models.TextField(null='ddd')),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand_name', models.CharField(max_length=100, null='imp')),
                ('price', models.CharField(default='₹10lakhs', max_length=150)),
                ('mileage', models.CharField(default='14kmpl', max_length=150)),
                ('index_car', models.CharField(default='2.3', max_length=150)),
                ('short_desc', models.TextField(null='desc')),
                ('feat', models.TextField(null='feat')),
                ('specs', models.TextField(null='specs')),
                ('variants', models.TextField(null='v')),
                ('category', models.CharField(max_length=100, null='imp')),
            ],
        ),
    ]
