# Generated by Django 3.0.8 on 2020-08-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='index_car',
        ),
    ]
