# Generated by Django 3.0.8 on 2020-08-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_carmodels_index_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='feat',
        ),
        migrations.RemoveField(
            model_name='carmodels',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='carmodels',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='carmodels',
            name='variants',
        ),
    ]
