# Generated by Django 3.0.8 on 2020-08-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200803_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodels',
            name='feat',
            field=models.TextField(default='1) Comfortable ride over all surfaces, noiseless suspension even over broken roads.<br>\n2) Improved overall interior space with increased storage spaces, including 1-litre bottle holders on all doors.<br>\n3) Largest-in-segment luggage compartment, well shaped too.<br>\n4) Lots of space inside the cabin.<br>\n*Disclaimer: Every car can have unique features and can be updated(open Admin then Car Models). Due to time constraints we are leaving this section empty as our main focus is analytics.'),
        ),
        migrations.AddField(
            model_name='carmodels',
            name='short_desc',
            field=models.TextField(default='The 2020 {{car.car_brand_name}} makes sense to those who are looking for a modern and spacious compact sedan. It looks contemporary, is feature laden, is easy to drive and being a {{car.car_brand_name}}, it promises to offer a peace of mind ownership experience.\n'),
        ),
        migrations.AddField(
            model_name='carmodels',
            name='specs',
            field=models.TextField(default='Mileage (upto):-- kmpl<br>\nEngine (upto): -- cc<br>\nBHP: --<br>\nTransmission: Automatic/manual<br>\nSeats: --<br>\nBoot Space: --L<br>\n*Disclaimer: Every car can have unique specs and can be updated(open Admin then Car Models). Due to time constraints we are leaving this section empty as our main focus is analytics .'),
        ),
        migrations.AddField(
            model_name='carmodels',
            name='variants',
            field=models.TextField(default='<tr class="table-active">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t1\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.Latest Price\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr class="table-success">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t2\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.25.15 Lakh*\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr class="table-warning">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t3\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.Latest Price\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr class="table-danger">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t4\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.Latest Price\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>\n<tr class="table-active">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t5\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.Latest Price\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>\n\t\t\t\t\t<tr class="table-success">\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t6\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tVariant \n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\tRs.Latest Price\n\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\n\t\t\t\t\t</tr>'),
        ),
    ]
