# Generated by Django 3.0.8 on 2020-08-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200803_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='short_desc',
        ),
    ]
