# Generated by Django 3.0.8 on 2020-08-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_carmodels_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='price',
        ),
    ]
