# Generated by Django 3.0.8 on 2020-08-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_carmodels_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandnames',
            name='dealership_loc',
        ),
    ]
