# Generated by Django 3.0.8 on 2020-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_brandnames_dealership_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandnames',
            name='dealership_loc',
            field=models.TextField(default='<option>Toyota ABC motors, Gurugram</option>\n<option>Toyota KLF motors, Faridabad</option>\n<option>Toyota Avenue motors, New Delhi</option>\n<option>Toyota Plaza motors, Mumbai</option>'),
        ),
    ]
