# Generated by Django 3.0.8 on 2020-08-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200801_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='index_car',
        ),
    ]
